; Generated by packaging/generate_context_menu.py; only app-owned keys.
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\image\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\image\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\image\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\image\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.3fr\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.3fr\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.3fr\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.3fr\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.apng\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.apng\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.apng\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.apng\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.arw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.arw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.arw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.arw\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avifs\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avifs\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avifs\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avifs\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr2\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr3\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr3\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr3\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cr3\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.crw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.crw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.crw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.crw\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cur\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cur\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cur\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.cur\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dcr\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dcr\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dcr\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dcr\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dds\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dds\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dds\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dds\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dib\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dib\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dib\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dib\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dng\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dng\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dng\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.dng\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.fff\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.fff\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.fff\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.fff\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heic\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heic\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heic\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heic\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.heif\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.hif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.hif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.hif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.hif\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.icns\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.icns\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.icns\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.icns\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.iiq\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.iiq\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.iiq\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.iiq\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.j2k\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.j2k\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.j2k\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.j2k\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jfif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jfif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jfif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jfif\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jp2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jp2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jp2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jp2\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpe\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpe\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpe\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpe\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpf\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpx\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpx\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpx\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpx\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.kdc\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.kdc\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.kdc\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.kdc\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mos\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mos\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mos\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mos\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mpo\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mpo\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mpo\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mpo\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mrw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mrw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mrw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mrw\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nef\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nef\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nef\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nef\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nrw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nrw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nrw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.nrw\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.orf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.orf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.orf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.orf\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pbm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pbm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pbm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pbm\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pcx\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pcx\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pcx\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pcx\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pef\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pef\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pef\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pef\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pgm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pgm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pgm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pgm\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pnm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pnm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pnm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.pnm\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ppm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ppm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ppm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ppm\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.psd\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.psd\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.psd\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.psd\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.qoi\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.qoi\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.qoi\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.qoi\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raf\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raw\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.raw\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgb\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgb\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgb\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgb\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgba\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgba\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgba\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rgba\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rw2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rw2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rw2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rw2\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rwl\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rwl\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rwl\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.rwl\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sgi\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sgi\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sgi\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sgi\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sr2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sr2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sr2\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.sr2\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.srf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.srf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.srf\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.srf\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.svg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.svg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.svg\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.svg\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tga\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tga\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tga\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tga\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tif\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tif\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.x3f\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.x3f\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.x3f\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.x3f\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xbm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xbm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xbm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xbm\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xpm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xpm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\PyPhotoEditor.exe"",0"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xpm\shell\PyPhotoEditor.Edit"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.xpm\shell\PyPhotoEditor.Edit\command"; ValueType: string; ValueData: """{app}\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".3fr"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".apng"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".arw"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".avif"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".avifs"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".bmp"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".cr2"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".cr3"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".crw"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".cur"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".dcr"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".dds"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".dib"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".dng"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".fff"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".gif"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".heic"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".heif"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".hif"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".icns"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".ico"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".iiq"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".j2k"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".jfif"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".jp2"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".jpe"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".jpeg"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".jpf"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".jpg"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".jpx"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".kdc"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".mos"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".mpo"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".mrw"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".nef"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".nrw"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".orf"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".pbm"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".pcx"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".pef"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".pgm"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".png"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".pnm"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".ppm"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".psd"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".qoi"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".raf"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".raw"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".rgb"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".rgba"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".rw2"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".rwl"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".sgi"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".sr2"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".srf"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".svg"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".tga"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".tif"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".tiff"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".webp"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".x3f"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".xbm"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\Applications\PyPhotoEditor.exe\SupportedTypes"; ValueType: string; ValueName: ".xpm"; ValueData: ""
