"""Generate installer associations from the same supported-format list as Open."""
from pathlib import Path
from pyphotoeditor.core.image_io import SUPPORTED_EXTENSIONS


def main():
    lines = ['; Generated by packaging/generate_context_menu.py; only app-owned keys.']
    for kind in ('image',)+SUPPORTED_EXTENSIONS:
        key = 'Software\\Classes\\SystemFileAssociations\\'+kind+'\\shell\\PyPhotoEditor.Edit'
        prefix = f'Root: HKCU; Subkey: "{key}"; '
        lines.append(prefix+'ValueType: string; ValueData: "Edit in PyPhotoEditor"; Flags: uninsdeletekey; Tasks: contextmenu')
        lines.append(prefix+'ValueType: string; ValueName: "Icon"; ValueData: """{app}\\PyPhotoEditor.exe"",0"; Tasks: contextmenu')
        lines.append(prefix+'ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Document"; Tasks: contextmenu')
        lines.append(f'Root: HKCU; Subkey: "{key}\\command"; ValueType: string; ValueData: """{{app}}\\PyPhotoEditor.exe"" -- ""%1"""; Tasks: contextmenu')
    for ext in SUPPORTED_EXTENSIONS:
        lines.append(f'Root: HKCU; Subkey: "Software\\Classes\\Applications\\PyPhotoEditor.exe\\SupportedTypes"; ValueType: string; ValueName: "{ext}"; ValueData: ""')
    Path(__file__).with_name('context-menu.iss').write_text('\n'.join(lines)+'\n',encoding='utf-8')


if __name__ == '__main__':
    main()
